### ISSUE TITLE
Huge memory leak (WIN)?

### ISSUE THREAD

**Issue by rwbc** [znxftw/rudim#23]
I compiled the current Rudim dev w/o any problems and errors, but I realized it seems to have an enormous memory leak?
It uses around 200MB additionally per second in test games. (CuteChessGUI)

There were other issues too, but this one has highest priority for now.

a test game
```
[Event "My Tournament"]
[Site "RWBC-ESPRESSO Win11Pro Ryzen7 5700G 3.8Ghz 32GB"]
[Date "2024.12.02"]
[Round "1.1.1"]
[White "Rudim_12-b366b93-64"]
[Black "Pixie_081-64"]
[Result "0-1"]
[ECO "A07"]
[GameDuration "00:02:49"]
[GameEndTime "2024-12-02T20:00:50.466 Mitteleuropäische Zeit"]
[GameStartTime "2024-12-02T19:58:00.769 Mitteleuropäische Zeit"]
[Opening "Reti"]
[PlyCount "94"]
[TimeControl "60+1"]
[Variation "King's Indian attack"]

1. Nf3 {book} d5 {book} 2. g3 {book} g6 {book} 3. c4 {book} e6 {book}
4. cxd5 {-0.30/6 1.56s} exd5 {+0.15/12 2.98s} 5. Nc3 {-0.30/6 1.56s}
Nf6 {+0.15/11 2.92s} 6. d4 {-0.30/6 1.56s} Nc6 {+0.20/11 2.85s}
7. Bd2 {-0.20/5 1.56s} Bg7 {+0.15/11 2.79s} 8. e3 {-0.20/5 1.55s}
O-O {+0.15/11 2.73s} 9. Bb5 {-0.15/5 1.53s} Rb8 {+0.15/11 2.67s}
10. O-O {-0.10/5 1.54s} Bg4 {+0.25/12 2.62s} 11. Re1 {-0.20/6 2.11s}
Ne4 {+0.30/11 2.56s} 12. Be2 {-0.30/6 2.08s} Qd7 {+0.30/11 2.51s}
13. Nxe4 {-0.25/6 2.06s} dxe4 {+0.45/13 2.46s} 14. Ng5 {-0.35/6 2.04s}
Bxe2 {+0.50/12 2.41s} 15. Qxe2 {-0.30/6 2.02s} Qd5 {+0.35/11 2.37s}
16. Nh3 {-0.35/5 2.00s} g5 {+0.30/11 2.32s} 17. Qh5 {-0.35/5 1.97s}
h6 {+0.50/11 2.28s} 18. Nf4 {-0.25/5 1.96s} Qd6 {+0.45/12 2.23s}
19. Ne2 {-0.49/6 1.94s} Ne5 {+0.40/12 2.19s} 20. Red1 {-0.53/6 1.93s}
Nf3+ {+0.35/11 2.15s} 21. Kg2 {-0.50/6 2.13s} Nxd2 {+0.40/11 2.11s}
22. Rxd2 {-0.45/6 2.11s} Rfe8 {+0.35/11 2.08s} 23. Re1 {-0.40/5 2.08s}
Rbd8 {+0.35/10 2.04s} 24. Nc3 {-0.38/5 2.05s} Qc6 {+0.30/10 2.01s}
25. Kg1 {-0.30/5 2.03s} Qe6 {+0.25/10 1.97s} 26. Rdd1 {-0.30/5 2.00s}
a6 {+0.30/11 1.94s} 27. a4 {-0.30/5 1.98s} Qc6 {+0.30/10 1.91s}
28. Qh3 {-0.30/5 1.95s} b5 {+0.30/11 1.88s} 29. axb5 {-0.15/6 1.93s}
axb5 {+0.20/12 1.85s} 30. Qf5 {-0.30/6 1.90s} b4 {+0.30/11 1.82s}
31. Ne2 {-0.25/6 1.87s} Rd5 {+0.25/12 1.79s} 32. Qg4 {-0.30/6 1.86s}
Qd6 {+0.30/11 1.77s} 33. Rc1 {-0.30/6 1.84s} Ra5 {+0.30/11 1.74s}
34. Qh5 {-0.25/5 1.81s} Ra2 {+0.35/11 1.72s} 35. Rb1 {-0.40/6 1.80s}
Qe6 {+0.30/10 1.69s} 36. g4 {-0.35/6 1.77s} c5 {+0.35/11 1.67s}
37. dxc5 {-0.30/6 1.75s} Bxb2 {+0.30/11 1.65s} 38. Nd4 {-0.28/6 1.74s}
Bxd4 {+1.30/12 1.63s} 39. exd4 {-1.30/7 1.72s} Qf6 {+1.30/12 1.61s}
40. Rf1 {-1.35/6 1.71s} Qxd4 {+1.25/12 1.58s} 41. Qxh6 {-1.35/6 1.53s}
Qxc5 {+1.20/11 1.57s} 42. Qb6 {-1.30/5 1.52s} Qxb6 {+12.25/12 1.55s}
43. Rbd1 {-10.35/5 1.51s} e3 {+15.95/13 1.53s} 44. fxe3 {-11.35/6 1.51s}
Qxe3+ {+M7/12 1.51s} 45. Kh1 {-489.94/7 1.50s} Qe4+ {+M5/12 1.49s}
46. Rf3 {-489.96/8 1.49s} Qxf3+ {+M3/12 1.48s} 47. Kg1 {-489.98/8 1.47s}
Qxd1# {+M1/12 1.46s, Black mates} 0-1
```

BTW here is the cmd output for go depth 8 from startpos:
(version change was my change because it makes no sense it would be still named 1.0 after you already had released version 1.2
which i also compiled around 2 years ago but had no time to test and it had no real time management at that time anyway)

```
uci
id name Rudim 1.2-b366b93 GS
id author Vishnu B
uciok
isready
readyok
position startpos
go depth 8
info depth 1 score cp 50 nodes 21 time 3 nps 7000
info depth 2 score cp 0 nodes 80 time 1 nps 101000
info depth 3 score cp 50 nodes 655 time 2 nps 378000
info depth 4 score cp 0 nodes 2136 time 11 nps 262909
info depth 5 score cp 40 nodes 17256 time 67 nps 300716
info depth 6 score cp 0 nodes 87901 time 466 nps 231864
info depth 7 score cp 35 nodes 674058 time 703 nps 1112527
info depth 8 score cp 0 nodes 3692568 time 5064 nps 883624
bestmove b1c3
```

Guenther (RWBC)

**Comment by znxftw** [comment]
Hi @rwbc !
Thanks for pointing this out - I had a similar hunch on #22 where I noticed memory in the pipeline was going haywire. I'll dig into it, thanks for pointing out. Time to get out my profiler. I'm not sure if this regression happened recently or even earlier 1.2 had it.

Also changed the version on my local, didn't notice that thanks - just started up this project again after a 2 year hiatus.

**Comment by znxftw** [comment]
Fixed - disabled move caching in  https://github.com/znxftw/rudim/commit/55ce9ac3b3233a56dfd0ca0adc885cb19d79ec3f  probably not a good idea to cache so many move possibilities - hit ratio is much lower than expected with all the unique positions once you go depth 7+

CLI name temporarily fixed in : https://github.com/znxftw/rudim/commit/6ba33d92da9dbf68356df71751574766c49e5002

https://github.com/znxftw/rudim/issues/25 - faster feedback for memory issues
https://github.com/znxftw/rudim/issues/24 - versioning fix

Thanks @rwbc

**Comment by rwbc** [comment]
Thanks! I will recompile later and test again, if the other issues still persist (illegal moves and strange blunders sometimes)
after the fix and if the memory abuse is really gone ;)

**Comment by rwbc** [comment]
Hi again Vishnu,

Ok I recompiled current version and the extremely excessive memory usage is indeed gone.
I played a quick test with 20 games at 0:30+0.5 (concurrency=1) and there also were no more illegal moves or weird blunders,
thus I assume they were (as I had hoped) just a symptom of the memory thing.

The memory is still growing slightly though and might become a problem in certain setups especially with GUIs
which have no `restart` option between the games. Regrettably the CuteChessGUI is one of those (unlike
the Cli version of it).
For Rudim this means as long as the program is not unloaded there e.g. in a long two players match or in games with high concurrency (and longer tc) it might become a problem again.

Isn't it possible to release all memory after game end, as it sure will receive `ucinewgame` at least?
Some number: after those 20 games the taskmanager was ~140 MB while the whole match lasted totally around 30 min.

Otherwise the only obvious thing to be fixed (for a relatively new - not so strong program) should be to avoid
three time repetitions when having quite some advantage in eval.
For this I will open a new issue.

Guenther

**Comment by znxftw** [comment]
Thanks for the detailed update Guenther.

I tried attaching a profiler while using BenchmarkDotNet to run some cases (15x run with depth 6/7/8 - multiple positions) and saw everything peaking at 25MB use. Also tried a fast-chess round robin tournament with 4 concurrent games, 100 rounds and there also saw it relatively low

Maybe as you mentioned GUI based CuteChess might be giving different uci commands - `ucinewgame` already clears up all the variables used (doesn't trigger GC explicitly or clear up all memory) https://github.com/znxftw/rudim/commit/9a6124b4a348e1422420eb406017c67b00c02f7e - I'll dig into  CuteChess let me get it on my local and try to see where it's going wrong.
