### ISSUE TITLE
Implement Transposition Tables

### ISSUE THREAD

**Issue by znxftw** [znxftw/rudim#33]
details TBD - brucemo's blog is a starting point, tried out on branch `tt` but not showing as great results as I thought - I might need to see if I'm doing things right

**Comment by rwbc** [comment]
If you need some other inspirations (also C#), I suggest:
https://github.com/lithander/MinimalChessEngine

**Comment by znxftw** [comment]
Thanks for the link - didn't know that C# engine existed.

I cross-checked with https://github.com/Tearth/Cosette and most things looked similar - will try to debug that branch and see how MinimalChessEngine implemented it

**Comment by znxftw** [comment]
fixed in #44
